name: PvPTeleport
main: org.c4k3.PvPTeleport.PvPTeleport
version: 1.5 #Bukkit 1.7.9 1938
depend: [MultiWorld]
commands:
  world:
    description: Teleports player between overworld and pvp world
    usage: Error. Please report at http://simpvp.net/forum
  pvplist:
    description: Lists all players in the pvp world
    usage: Error. Please report at http://simpvp.net/forum