name: PvPTeleport
main: net.simpvp.PvPTeleport.PvPTeleport
version: 1.8
api-version: 1.13
commands:
  world:
    description: Teleports player between overworld and pvp world.
    usage: Error. Please report at https://github.com/C4K3/PvPTeleport
  pvplist:
    description: Lists all players in the pvp world.
    usage: Error. Please report at https://github.com/C4K3/PvPTeleport
